version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_DATABASE: rust_mongodb
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo:
